---
title: "Weight of Fish"
author: "Kimberly Lemus Munoz"
date: "summer 2022"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

```{r}
All_Fish <-read.csv(file="Fish.csv")
```

```{r}
Perch <- filter(All_Fish, Species =="Perch")
```


```{r}
Perch <-select(Perch, -Species)
```





# Predicting Fish Weight


## Perch


```{r}
regsubsets.out <-
    regsubsets(Weight ~ .,
               data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```





### Best Models

The best model is lenght1,lenght2,lenght3 height anad width.The for is is because has the highest adjected r value, it is the one highest on the y-axis.


### Best Two regressor model


## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements